version: '2'

services:
  dbserver:
    restart: always
    image: mariadb:10.2
    ports: 
      - 33308:3306
    volumes:
      - docker/database:/docker-entrypoint-initdb.d
      - blogapi-db:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: blogapi
      MYSQL_ROOT_HOST: "%"
      MYSQL_DATABASE: blogapi
  
  blogapi:
    restart: always
    image: hectorvent/blogapi
    ports:
      - 8080:8080
    environment:
      DATABASE_USER: root
      DATABASE_PASSWORD: blogapi
      DATABASE_URL: jdbc:mysql://dbserver:3306/blogapi?characterEncoding=UTF-8&useSSL=false
    depends_on:
      - dbserver

volumes:
  blogapi-db: